### ISSUE TITLE
Depreciate the use of `task.storage[:turing_predicts]`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#129]
Since we have now got an enhanced `VarInfo` type to store all MCMC states, we should consider depreciate using `task.storage[:turing_predicts]`. For example, the following lines need to be updated

- https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L113

**Comment by xukai92** [comment]
Besides https://github.com/yebai/Turing.jl/blob/master/src/samplers/hmc.jl#L113, there are another two places we use `Task.storage`, which are

1. https://github.com/yebai/Turing.jl/blob/master/src/core/container.jl#L187L188
2. https://github.com/yebai/Turing.jl/blob/master/src/samplers/sampler.jl#L64L66

Although our new `VarInfo` store all MCMC states, it doesn't store the original Julia value, i.e. it stores `x[1]`, `x[2]`, ..., instead of the original `x`.

We tackled this problem in our Gibbs sampler by using `varInfo2samples()` (https://github.com/yebai/Turing.jl/blob/master/src/samplers/gibbs.jl#L81) to reconstruct the original Julia value. We can do the same thing for everywhere we uses `Task.storage`, but

1. Our `varInfo2samples()` is not generalized. It only deals with simple array reconstruction, i.e. combing `x[1]`, `x[2]`, ... to `x`.
2. Calling `varInfo2samples()` (i.e. reconstruct Julia type) in each `values(p::Particle)` seems to be expansive.

Do you think we should genealize `varInfo2samples()`? 

Actually I also remember you mentioned it's good to just use the flatten type (as `Mamba` needs it). If this approach is better, I guess we could just abandon the original Julia value and use the flatten version everywhere? If so, the removal of `Task.storage` will also be quite easy.

**Comment by yebai** [comment]
Let's just use the flatten type and drop `varInfo2samples` from the code.

**Comment by yebai** [comment]
Closed by PR #123 
Ref: #133
