### ISSUE TITLE
support resume MCMC sampling, e.g. `resume(s::Chain, num_iter)`

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#152]
Migrated from #96.

TODOs:
- [x] Add `Sampler` as a field of `Chain`
- [x] Add model as a field of `Chain`
- [x] Add last vi as a field of `Chain`
- [x] Support resume for HMC
- [x] Support resume for PG
- [x] Support resume for Gibbs
- [x] Add a `resume(s::Chain, num_iter)` wrapper

**Comment by xukai92** [comment]
After thinking possible implementations of this feature, I ended up believing the following interface is the most preferable

```julia
chain = sample(model, alg)
sample(model, alg; resume_from=chain)
```

The good point about this is that we can reuse most of the code in `sample()`. For the enriched-chain type, we just need to additionally store sampler (for adaptive sampler we need it because of the adaptive parameters), model and last vi; in `sample()`, we check if the `resume_from` is provided:

- if so, instead of initialising by calling `model()`, just fetch the vi from provided chain & instead of creating a new sampler, use the provided one;
- if not, do sample as before.

Of course, by introducing this interface, we can also create a wrapper called `resume()` suggested before.

One question here is that:

Should the returned chain containing the samples for 2 runs or just the new run, i.e. appending samples to the new chain or create a new one?

How do you think?

**Comment by yebai** [comment]
Looks sensible to me!

> Should the returned chain containing the samples for 2 runs or just the new run, i.e. appending samples to the new chain or create a new one?

If we resume running one chain (e.g. continuing from previous `VarInfo`) then we should store all samples in one chain. Otherwise, we should return a new chain.

**Comment by xukai92** [comment]
Cool. Make sense to me. Let me implement to this design

**Comment by xukai92** [comment]
Closed by https://github.com/yebai/Turing.jl/pull/278
