### ISSUE TITLE
Save parameter adaption trajectory for HMCDA, NUTS

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#206]
It's helpful to save parameter adaption history in `Sampler.info` for later inspection, e.g. inspecting dual averaging divergence. 

For example
- epsilon, 
- simulated Hamiltonian length: L'*epsilon, where L' is the actual number of leapfrog steps before rejection.

**Comment by xukai92** [comment]
I started to do this in #267 (e.g. commit 34819c30e94248ea797766b0a539a21070b23165). I finally add a more-riched interface to generate sampler, saying `Sample(vi, spl)`, which combines both info from `VarInfo` and `spl.info`. This is pretty neat for HMC(DA) and NUTS but seems Gibbs is still bit messy because for samplers like PG the `spl.info` doesn't have information like `epsilon` - so in order to make each sample from the Gibbs sample, I currently manually check and record the information from the previous HMC sampler and add them to the PG one so each sample have the same dimension of information (otherwise Chain will be broken).

**Comment by xukai92** [comment]
Closed by PR #267 and in favor of issue https://github.com/yebai/Turing.jl/issues/269
