### ISSUE TITLE
Solving the Lighthouse Problem

### ISSUE THREAD

**Issue by lstagner** [yebai/Turing.jl#209]
I'm trying to solve the [lighthouse problem](http://web.gps.caltech.edu/classes/ge193.old/practicals/practical3/Lighthouse.pdf) and I have encountered an error on master

```julia
using Turing

function generate_data(α,β,n=100)
    θ = -pi/2 + pi*rand(n)
    x = α .+ β*tan.(θ)
    return x
end

@model lighthouse(x)
    θ ~ Uniform(-pi/2,pi/2)
    α ~ Uniform(-5.0,5.0)
    β ~ Uniform(0.0,5.0)
    for i=1:length(x)
        x[i] ~ α + β*tan(θ)
    end
    return (α, β)
end
```
```
type Symbol has no field args
```

Am I doing something wrong or does Turing not yet support this type of problem?

**Comment by xukai92** [comment]
Nice question. 

The error occurs because the right hand side of the `~` notation should always be a distribution, which tells Turing a variable is distributed from a distribution. In you problem, you should write your likelihood, P(x|α, β), there (i.e. point 4 in your sheet), which should be

```julia
x[i] ~ Cauchy(α, β)
```

(Ref: http://astro.ic.ac.uk/sites/default/files/CLT%20and%20Lighthouse%20Problem.pdf)

Also notice that this likelihood actually doesn't have theta inside. So you model should be

```julia
@model lighthouse(x) = begin
    α ~ Uniform(-5.0,5.0)
    β ~ Uniform(0.0,5.0)
    for i=1:length(x)
        x[i] ~ Cauchy(α, β)
    end
end
```

Then you can run inference by

```julia
# Generate 100 data points with α = 2 and β = 2, and run HMC (or any other sampler you want)
chain = sample(lighthouse(generate_data(2, 2, 100)), HMC(1000, 0.2, 4))
```

Then the estimate of the location of the lighthouse could be got by

```julia
α = mean(chain[:α])
β = mean(chain[:β])
```

**Comment by lstagner** [comment]
Thanks for the quick response.

Is it not possible to compose different distributions to create a new distribution object e.g. `α + β*tan(θ)`
Is it planned?

**Comment by yebai** [comment]
Hi Turing uses distribution object from the [`Distributions.jl`](https://github.com/JuliaStats/Distributions.jl) package, so new distribution object should be added to the `Distributions.jl` package. Alternatively, if you don't mind adding a small Gaussian noise, the model can be written as

```julia
@model lighthouse(x) = begin
    θ ~ Uniform(-pi/2,pi/2)
    α ~ Uniform(-5.0,5.0)
    β ~ Uniform(0.0,5.0)
    for i=1:length(x)
        x[i] ~ Normal(α + β*tan(θ), 1)
    end
    return (α, β)
end
```

**Comment by lstagner** [comment]
Thanks @yebai 

Unfortunately, using a Normal distribution makes the problem intractable. Not even Stan could get a reasonable solution.
