### ISSUE TITLE
Gibbs sampler is broken

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#213]
It seems PR #199 is causing the Gibbs sampler producing inaccurate results.

**Comment by xukai92** [comment]
Do you mean the error in the Gibbs constructor or other?

**Comment by yebai** [comment]
Yes, I am refering to the gibbs constructor.

**Comment by xukai92** [comment]
It seems that it just because I changed the number of iterations of the Gibbs sampler to only 50 because I thought that was bit slow. I changed it back to 500 in this commit: https://github.com/yebai/Turing.jl/commit/fd6e3e6cf135928ebff9fe23ca767c69cbec71bb.

I looked into some other Gibbs result (with long run), which seems to be fine (e.g. `gibbs.jl`).

However, this test file is supposed to test the constructor only, can we just remove the numerical checks?
