### ISSUE TITLE
Development branch is broken.

### ISSUE THREAD

**Issue by yebai** [yebai/Turing.jl#22]
@xukai92 could you have a look at https://travis-ci.org/yebai/Turing.jl/builds/153336076 and see what breaks the development branch? Seems like merging HMC introduces some incompatibility issues.

**Comment by xukai92** [comment]
I found that the issue comes from `@assume` marco used in the file `src/distributions/bnp.jl`. Basically if you comment out Line 11 `@assume c ~ Categorical(weights)` in `src/distributions/bnp.jl`, all tests pass.

The reason this give error is that I added some `dprintln()` functions for each marco in `src/core/compiler.jl` to help debug the compiler, and the macro in the `bnp.jl` file is translated before Julia see the `dprintln()` function (I guess).

The solution to this is simply removing the `dprintln()` functions in `src/core/compiler.jl` but we will lose the debugging statements for the compiler. May be it's better to change Line 11 of `src/distributions/bnp.jl` somehow so that we can keep the debugging functions in `src/core/compiler.jl`.

BTW, I wonder is it good to use the compiler within Turing or it should be ideally used only outside Turing?

**Comment by yebai** [comment]
I've fixed this issue by moving the definition of `dprintln` before including `bnp.jl`, the reason should be self-evident - see f4602daade4d6a9f0f617cebc94d5b7e3bbb9be0 for details.

**Comment by yebai** [comment]
CI for development is still broken (see https://travis-ci.org/yebai/Turing.jl/jobs/153668257). It seems some further issues still exist.

**Comment by xukai92** [comment]
Fix by adding `DualNumbers` to the dependency file `REQUIRE` (CI passed: https://travis-ci.org/yebai/Turing.jl/builds/153704082).
