### ISSUE TITLE
Re-organise/re-structure the source code

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#31]
We need a plan for better organisation of the source code. We can collect issues regarding this here.

For example, code in `/src/core/intrinsic.jl` seems to be only relevant to samplers (and a bit messy). It would be easy to maintain if we move it to `/src/samplers/` (or sub-folder).

**Comment by adscib** [comment]
I am unhappy about the frequent use of `include`. For me it is often the case that I look at a file, see that it uses some undefined functions, and then I don't know where to locate them. In order to find the definition not only do I need to search all the files included from this one, but also all files that include it, perhaps indirectly. In other words I need to traverse the hierarchy of source files in both directions, which I think is very messy and gave me many headaches. But then again I don't like dynamic languages in general.

It would be nice if we could divide Turing into smaller modules to keep things manageable. The code I wrote doesn't do anything clever with dynamic loading, so such refactoring shouldn't be difficult.

**Comment by xukai92** [comment]
@adscib I have the same feeling as you. 

For the problem you mentioned, I agree that modularisation is a good solution. Also, we could add "where this function is located" in the comment section, and in IDEs like Juno (Atom), we can check it quickly by using the documentation toggle feature.

**Comment by xukai92** [comment]
I merged `sampler.jl` and `intrinsic.jl`. I guess that's the only obvious thing we can do now and we've already removed those unused files. Shall we close this issue?

**Comment by yebai** [comment]
Closed by #54
