### ISSUE TITLE
Tests not pass for Julia v0.5

### ISSUE THREAD

**Issue by xukai92** [yebai/Turing.jl#32]
Tests do not pass for v0.5. 

I looked into the errors and also did the test on my machine, finding that the `SMC` and `PG` engines seem to be broken. I guess it may be resulted from the update of `task.c` ?

**Comment by yebai** [comment]
The issues are causes by

1. A bug for incorrect overriding previously defined functions in Julia 0.5: fixed by avoiding overriding function definitions in tests. 
1. A bug in TArray: to be fixed

There are also various warning messages when loading Turing in Julia 0.5. It makes sense to keep a separate branch for Julia 0.5 until all issues are addressed.

**Comment by yebai** [comment]
Fixed by #38
