### ISSUE TITLE
Macro-free interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [yebai/Turing.jl#336]
It would be easier for other developers to target the functionality of the package if a function-based interface existed instead of just the macros.

**Comment by yebai** [comment]
I think this is a documentation issue, the interface is already function-based. This is because the `@model` macro will generate a standard Julia function, but with pre-defined parameter signature so that inference algorithms can interact with the model. We posted some interface design notes in https://github.com/yebai/Turing.jl/issues/104. Perhaps take a look and see whether that is what you want, if not, we can try to improve the compiler design.

**Comment by xukai92** [comment]
Yes it's actually a doc issue.

@yebai: I think it should be added to https://github.com/yebai/Turing.jl/wiki/Advanced-usages right?

@ChrisRackauckas: I will finish the documentation on this along with working on https://github.com/JuliaDiffEq/DiffEqBayes.jl/issues/1

**Comment by xukai92** [comment]
Wiki updated here: https://github.com/yebai/Turing.jl/wiki/Advanced-usages#avoid-using-model-macro

**Comment by xukai92** [comment]
TODOs
- [x] doc how `@model` works
- [ ] doc how `~` works

**Comment by xukai92** [comment]
I'm not going to doc the `~` macro as it will be removed soon.

**Comment by xukai92** [comment]
- [ ] Update https://github.com/yebai/Turing.jl/wiki/Advanced-usages#avoid-using-model-macro as we no longer able to use `~` standalone
