### ISSUE TITLE
Log model evidence and/or weights may be incorrect

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#359]
Hi all !

## Log model evidence
For `PMMH` and `IPMCMC` the marginal likelihood p(y_1,...,y_T) estimate is needed.
Is it what is stored in `ParticleContainer.logE` and computed within `Base.consume(pc :: ParticleContainer)` with `increase_logevidence` ?

If so, I believe that there is an error. Since `pc.logWs` accumulates the vector (of size # particles) of log evidence along time, i.e. `pc.logWs=sum_{l=1:t}(logW_l)`, thus `z2 - z1 = log(sum_i(sum_{l=1:t} W_l)) - log(sum_i(sum_{l=1:t-1} W_l))` is not equal to `logZ_t =  log(sum_i(W_t))` which should be the log evidence increment.

I believe the subtraction should be between old and new `pc.logWs` (before and after consuming particles and thus incrementing these `logWs`), i.e.
`logZ_t =  log(sum_i(exp(sum_{l=1:t}(logW_l) - sum_{l=1:t-1}(logW_l))))`.

Therefore a fix would be:
```julia
old_logWs = copy(pc.logWs)
... consume particles
logWs = copy(pc.logWs) - old_logWs
Ws = exp(logWs-maximum(logWs))
logZ = log(sum(Ws)) + maximum(logWs)
increase_logevidence(pc, logZ)
```

## Weights
Btw, I don't really understand the `weights(pc :: ParticleContainer)` function
```julia
logWs = pc.logWs
Ws = exp(logWs-maximum(logWs))
Ws = Ws ./ sum(Ws)
```
since at the end `Ws` is not `exp(logWs)` or neither `exp(logWs)/sum(exp(logWs))`.

Best regards,
Emile

**Comment by yebai** [comment]
Hi @emilemathieu,

Pls find below for some explanations. You are right that we need some further refactoring to make the code easier to follow for new developers. We can keep the discussion going until we collect enough input.

> Is it what is stored in ParticleContainer.logE and computed within Base.consume(pc :: ParticleContainer) with increase_logevidence ?

`ParticleContainer.logE` stores the accumulated model evidence p(y1, y2, ... yt | theta). `pc.logWs` stores the un-normalised incremental log likelihoods between two consecutive resampling steps, i.e., p(y_m, ..., y_n | theta) where m index the first data item arriving after the previous resampling step, and n the current data item. In order to compute the incremental log-likelihood, we need to subtract the normalisation constant z1, which in most cases equal to `log(N)`. 

>  I don't really understand the `weights(pc :: ParticleContainer)` function

This is a small numerical applied here in order trick to stably compute `sum(exp(logWs))`. Perhaps a better way of writing the code is

```julia
logWs = pc.logWs
Ws      = exp(logWs - logsumexp(logWs)) # logsumexp will ensure numerical stability. 
```

**Comment by twgr** [comment]
Thanks Hong. I just had a chat with Emile about this and we went through it and confirmed that the implementation is correct.

**Comment by emilemathieu** [comment]
Indeed, thanks Hong and Tom !
My last question is silly, substracting `maximum(logWs)` to each `logWs` does not change anything.

The computation for the incremental log marginal likelihood is a bit trickier because of adaptive re sampling but is indeed correct ! My bad for these wrong assertions.
